# Generated by Django 3.0.5 on 2020-05-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
