# Generated by Django 2.2.5 on 2019-09-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_id',
        ),
    ]
