# Generated by Django 2.2.5 on 2019-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descreption', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
