# Generated by Django 2.2.5 on 2019-09-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descreption',
            new_name='description',
        ),
    ]
